### ISSUE TITLE
error: declaration of ‘u8’ shadows a global declaration [9221]

### ISSUE THREAD

**Issue by knuxyl** [DLTcollab/sse2neon#673]
Build on Radxa Rock 5B Gentoo Linux 6.15.6
gcc (Gentoo Hardened 14.3.0 p8) 14.3.0

`sse2neon.h:9221:16: error: declaration of ‘u8’ shadows a global declaration [-Werror=shadow]`
```
 9221 |     uint8x16_t u8 = vaeseq_u8(vreinterpretq_u8_m128i(a), vdupq_n_u8(0));
      |                ^~
```
Temporarily replacing `u8` with `u8a` at line `9221` and all references in the function `FORCE_INLINE __m128i _mm_aeskeygenassist_si128` seems to have fixed it. I think it just needs a different name.
